import { annotationTemplate, evaluateJudged, judgedMarkdown, judgedCSV, sourceFingerprint } from './judged.mjs';
const safe = s => String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const pct = x => (100 * x).toFixed(1) + '%';
const download = (value, name, mime) => { const blob = new Blob([value], { type:mime }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url), 1000); };

export function createJudgedPanel({ getSource, notify }) {
  let draft = '', report = null, resultKey = '';
  const fingerprint = () => sourceFingerprint(getSource());
  const clear = () => { report = null; resultKey = ''; };
  function render(panel) {
    if (report && resultKey !== JSON.stringify([fingerprint(), draft])) clear();
    panel.innerHTML = `<p class="muted">v1.0 · Manual relevance evaluation. Export an unjudged template, inspect chunk IDs, then manually label ALL relevant chunks for each question. No labels or results are generated by AI.</p>
      <div class="actions"><button id="judgeTemplate">✧ Create annotation template</button><button id="judgeDownloadTemplate" disabled>↓ Template JSON</button><button id="judgeDataset">↓ Save dataset JSON</button></div>
      <label class="compare-label" for="judgmentsInput">Judged dataset (JSON)</label><textarea id="judgmentsInput" class="field compare-source" spellcheck="false" aria-label="Manually judged retrieval dataset"></textarea>
      <div class="actions"><button class="primary" id="judgeRun">◎ Evaluate judgments</button><button id="judgeJson" disabled>↓ JSON</button><button id="judgeMd" disabled>↓ Markdown</button><button id="judgeCsv" disabled>↓ CSV</button></div><div id="judgeResults" aria-live="polite"></div>`;
    const area = panel.querySelector('#judgmentsInput'); area.value = draft;
    const setExports = on => { for (const id of ['judgeJson','judgeMd','judgeCsv']) panel.querySelector('#' + id).disabled = !on; };
    area.oninput = () => { draft = area.value; clear(); setExports(false); panel.querySelector('#judgeResults').textContent = ''; panel.querySelector('#judgeDownloadTemplate').disabled = true; };
    panel.querySelector('#judgeTemplate').onclick = () => { try { const t = annotationTemplate(getSource()); draft = JSON.stringify(t,null,2); area.value = draft; clear(); setExports(false); panel.querySelector('#judgeDownloadTemplate').disabled = false; panel.querySelector('#judgeResults').textContent = 'Template generated. Add query objects with id, query, and relevant fixed/heading-aware chunk ID arrays. Inspect the chunks field. Set annotationStatus to judged and supply annotator and annotationDate after labeling.'; notify('Unjudged annotation template created'); } catch (e) { notify(e.message); } };
    panel.querySelector('#judgeDownloadTemplate').onclick = () => download(draft, 'emetivra-unjudged-template.json', 'application/json');
    panel.querySelector('#judgeDataset').onclick = () => { try { const dataset = JSON.parse(draft); if (!dataset || typeof dataset !== 'object' || Array.isArray(dataset)) throw Error('Enter a JSON dataset.'); download(JSON.stringify(dataset, null, 2), 'emetivra-annotations.json', 'application/json'); } catch(e) { notify('Cannot export dataset: ' + e.message); } };
    panel.querySelector('#judgeRun').onclick = () => { try { const data = JSON.parse(draft); report = evaluateJudged(getSource(), data); resultKey = JSON.stringify([fingerprint(), draft]); setExports(true); const html = Object.entries(report.strategies).map(([strategy, s]) => `<div class="finding"><h3>${safe(strategy)} · ${s.chunkCount} chunks</h3><div class="metric-row">${[['P@3','precisionAtK'],['Recall@3','recallAtK'],['Hit@3','hitAtK'],['MRR@3','reciprocalRankAtK'],['nDCG@3','ndcgAtK']].map(([name,key])=>`<div class="metric"><small>${name}</small><strong>${pct(s.metrics[key])}</strong></div>`).join('')}</div></div>`).join(''); panel.querySelector('#judgeResults').innerHTML = `<p class="muted">${report.provenance.queryCount} manually judged queries · ${safe(report.provenance.annotator)} · ${safe(report.provenance.annotationDate)}. Labels are user supplied and not verified.</p>` + html + report.limitations.map(x=>`<p class="muted">• ${safe(x)}</p>`).join(''); notify('Judged evaluation complete'); } catch (e) { clear(); setExports(false); panel.querySelector('#judgeResults').textContent = e.message; notify('Judged evaluation error: ' + e.message); } };
    const valid = () => { if (!report || resultKey !== JSON.stringify([fingerprint(), draft])) { setExports(false); notify('Dataset or source changed. Evaluate again.'); return false; } return true; };
    panel.querySelector('#judgeJson').onclick = () => valid() && download(JSON.stringify(report,null,2), 'emetivra-judged-evaluation.json', 'application/json');
    panel.querySelector('#judgeMd').onclick = () => valid() && download(judgedMarkdown(report), 'emetivra-judged-evaluation.md', 'text/markdown');
    panel.querySelector('#judgeCsv').onclick = () => valid() && download(judgedCSV(report), 'emetivra-judged-evaluation.csv', 'text/csv');
  }
  return { render };
}